# Generated by Django 3.2.9 on 2021-11-03 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='nome')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='preço')),
                ('estoque', models.IntegerField(verbose_name='quantidade em estoque')),
            ],
        ),
    ]
