# Generated by Django 3.2.9 on 2021-11-10 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gerencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='nome')),
                ('codigo', models.CharField(max_length=100, verbose_name='codigo')),
                ('cargo', models.CharField(max_length=100, verbose_name='cargo')),
            ],
        ),
    ]
